import {
  Audit,
  AuditLog,
  Invitation,
  NonConformity,
  Organization,
  QmsDocument,
  User,
} from './models';

const now = new Date();
const iso = (offsetDays = 0) =>
  new Date(now.getTime() + offsetDays * 86_400_000).toISOString();

export const seedOrganizations: Organization[] = [
  {
    id: 'org-1',
    name: 'Demo Corp',
    slug: 'demo-corp',
    createdBy: 'user-super',
    createdAt: iso(-90),
    timezone: 'Europe/Paris',
  },
  {
    id: 'org-2',
    name: 'Acme Industries',
    slug: 'acme-industries',
    createdBy: 'user-super',
    createdAt: iso(-45),
    timezone: 'Europe/Paris',
  },
];

export const seedUsers: User[] = [
  {
    id: 'user-super',
    email: 'super@qms.com',
    firstName: 'Sarah',
    lastName: 'Connor',
    role: 'SUPER_ADMIN',
    orgId: null,
    isActive: true,
    createdAt: iso(-120),
  },
  {
    id: 'user-admin',
    email: 'admin@demo.com',
    firstName: 'Alice',
    lastName: 'Martin',
    role: 'ORG_ADMIN',
    orgId: 'org-1',
    isActive: true,
    createdAt: iso(-90),
  },
  {
    id: 'user-qm',
    email: 'qm@demo.com',
    firstName: 'Quentin',
    lastName: 'Moreau',
    role: 'QUALITY_MANAGER',
    orgId: 'org-1',
    isActive: true,
    createdAt: iso(-80),
  },
  {
    id: 'user-auditor',
    email: 'auditor@demo.com',
    firstName: 'Alex',
    lastName: 'Dupont',
    role: 'AUDITOR',
    orgId: 'org-1',
    isActive: true,
    createdAt: iso(-70),
  },
  {
    id: 'user-emp',
    email: 'employee@demo.com',
    firstName: 'Emma',
    lastName: 'Bernard',
    role: 'EMPLOYEE',
    orgId: 'org-1',
    isActive: true,
    createdAt: iso(-60),
  },
  {
    id: 'user-emp2',
    email: 'paul@demo.com',
    firstName: 'Paul',
    lastName: 'Petit',
    role: 'EMPLOYEE',
    orgId: 'org-1',
    isActive: true,
    createdAt: iso(-30),
  },
];

export const seedInvitations: Invitation[] = [
  {
    id: 'inv-1',
    email: 'newhire@demo.com',
    orgId: 'org-1',
    role: 'EMPLOYEE',
    token: 'token-demo-pending',
    expiresAt: iso(7),
    status: 'PENDING',
    invitedBy: 'user-admin',
    createdAt: iso(-2),
  },
];

export const seedDocuments: QmsDocument[] = [
  {
    id: 'doc-1',
    title: 'Quality Manual',
    type: 'MANUAL',
    status: 'APPROVED',
    currentVersionId: 'docv-1b',
    orgId: 'org-1',
    createdBy: 'user-qm',
    createdAt: iso(-60),
    updatedAt: iso(-10),
    metadata: [
      { key: 'ISO Clause', value: '4.3' },
      { key: 'Owner', value: 'Quality Department' },
      { key: 'Review Frequency', value: '12 months' },
    ],
    versions: [
      {
        id: 'docv-1a',
        documentId: 'doc-1',
        versionNumber: '1.0',
        filePath: '/mock/quality-manual-v1.pdf',
        fileName: 'quality-manual-v1.pdf',
        fileSize: 245_120,
        mimeType: 'application/pdf',
        createdAt: iso(-60),
        createdBy: 'user-qm',
      },
      {
        id: 'docv-1b',
        documentId: 'doc-1',
        versionNumber: '1.1',
        filePath: '/mock/quality-manual-v1-1.pdf',
        fileName: 'quality-manual-v1-1.pdf',
        fileSize: 251_800,
        mimeType: 'application/pdf',
        createdAt: iso(-10),
        createdBy: 'user-qm',
      },
    ],
  },
  {
    id: 'doc-2',
    title: 'Supplier Evaluation Procedure',
    type: 'PROCEDURE',
    status: 'REVIEW',
    currentVersionId: 'docv-2a',
    orgId: 'org-1',
    createdBy: 'user-qm',
    createdAt: iso(-30),
    updatedAt: iso(-3),
    metadata: [
      { key: 'ISO Clause', value: '8.4' },
      { key: 'Owner', value: 'Purchasing' },
    ],
    versions: [
      {
        id: 'docv-2a',
        documentId: 'doc-2',
        versionNumber: '1.0',
        filePath: '/mock/supplier-eval.pdf',
        fileName: 'supplier-eval.pdf',
        fileSize: 88_400,
        mimeType: 'application/pdf',
        createdAt: iso(-30),
        createdBy: 'user-qm',
      },
    ],
  },
  {
    id: 'doc-3',
    title: 'Calibration Record Template',
    type: 'RECORD',
    status: 'DRAFT',
    currentVersionId: 'docv-3a',
    orgId: 'org-1',
    createdBy: 'user-admin',
    createdAt: iso(-5),
    updatedAt: iso(-5),
    metadata: [{ key: 'Owner', value: 'Maintenance' }],
    versions: [
      {
        id: 'docv-3a',
        documentId: 'doc-3',
        versionNumber: '1.0',
        filePath: '/mock/calibration-record.docx',
        fileName: 'calibration-record.docx',
        fileSize: 32_100,
        mimeType:
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        createdAt: iso(-5),
        createdBy: 'user-admin',
      },
    ],
  },
];

export const seedNonConformities: NonConformity[] = [
  {
    id: 'nc-1',
    reference: 'NC-2026-001',
    title: 'Damaged packaging on incoming shipment',
    description:
      'Shipment from supplier ABC arrived with 8 boxes showing visible damage; 2 boxes had broken seals.',
    severity: 'MAJOR',
    status: 'IN_PROGRESS',
    assignedTo: 'user-qm',
    reportedBy: 'user-emp',
    orgId: 'org-1',
    createdAt: iso(-12),
    updatedAt: iso(-2),
    rootCauses: [
      {
        id: 'rc-1',
        ncId: 'nc-1',
        hypothesis: 'Inadequate packaging spec in PO',
        causeType: 'PROCESS',
        isConfirmed: true,
        createdAt: iso(-10),
      },
      {
        id: 'rc-2',
        ncId: 'nc-1',
        hypothesis: 'Mishandling during transit',
        causeType: 'PEOPLE',
        isConfirmed: false,
        createdAt: iso(-10),
      },
    ],
    actions: [
      {
        id: 'act-1',
        ncId: 'nc-1',
        causeId: 'rc-1',
        description: 'Update PO template with packaging requirements',
        assignedTo: 'user-admin',
        dueDate: iso(7),
        status: 'IN_PROGRESS',
        createdAt: iso(-9),
      },
      {
        id: 'act-2',
        ncId: 'nc-1',
        causeId: 'rc-1',
        description: 'Train procurement team on new template',
        assignedTo: 'user-qm',
        dueDate: iso(14),
        status: 'PENDING',
        createdAt: iso(-9),
      },
    ],
  },
  {
    id: 'nc-2',
    reference: 'NC-2026-002',
    title: 'Out-of-spec dimensions on batch B-204',
    description: 'CMM measurement showed 0.12mm deviation, tolerance is 0.05mm.',
    severity: 'CRITICAL',
    status: 'OPEN',
    assignedTo: null,
    reportedBy: 'user-emp2',
    orgId: 'org-1',
    createdAt: iso(-3),
    updatedAt: iso(-3),
    rootCauses: [],
    actions: [],
  },
  {
    id: 'nc-3',
    reference: 'NC-2026-003',
    title: 'Missing operator signature on QC record',
    description: 'Form QC-022 from 2026-05-08 missing operator signature.',
    severity: 'MINOR',
    status: 'CLOSED',
    assignedTo: 'user-qm',
    reportedBy: 'user-emp',
    orgId: 'org-1',
    createdAt: iso(-25),
    updatedAt: iso(-15),
    closedAt: iso(-15),
    rootCauses: [
      {
        id: 'rc-3',
        ncId: 'nc-3',
        hypothesis: 'Operator distraction',
        causeType: 'PEOPLE',
        isConfirmed: true,
        createdAt: iso(-23),
      },
    ],
    actions: [
      {
        id: 'act-3',
        ncId: 'nc-3',
        causeId: 'rc-3',
        description: 'Add signature reminder in QC SOP',
        assignedTo: 'user-qm',
        dueDate: iso(-16),
        status: 'DONE',
        completedAt: iso(-16),
        createdAt: iso(-22),
      },
    ],
  },
];

export const seedAudits: Audit[] = [
  {
    id: 'aud-1',
    title: 'Q2 Internal Audit — Production',
    type: 'INTERNAL',
    scheduledDate: iso(14),
    auditorId: 'user-auditor',
    status: 'PLANNED',
    orgId: 'org-1',
    scope: 'Production line A, including incoming inspection and QC.',
    createdAt: iso(-5),
    checklist: [
      {
        id: 'chk-1',
        auditId: 'aud-1',
        item: 'Verify operator training records up to date',
        finding: '',
        evidence: '',
        conformity: null,
      },
      {
        id: 'chk-2',
        auditId: 'aud-1',
        item: 'Check calibration certificates valid',
        finding: '',
        evidence: '',
        conformity: null,
      },
    ],
    findings: [],
  },
  {
    id: 'aud-2',
    title: 'Supplier Audit — ABC Logistics',
    type: 'SUPPLIER',
    scheduledDate: iso(-20),
    auditorId: 'user-auditor',
    status: 'COMPLETED',
    orgId: 'org-1',
    scope: 'Packaging and shipping procedures at ABC Logistics warehouse.',
    createdAt: iso(-40),
    checklist: [
      {
        id: 'chk-3',
        auditId: 'aud-2',
        item: 'Inspect packaging area',
        finding: 'Packaging materials stored without humidity control',
        evidence: 'Photos taken; humidity log absent.',
        conformity: 'NON_CONFORM',
      },
      {
        id: 'chk-4',
        auditId: 'aud-2',
        item: 'Verify shipping log integrity',
        finding: 'Log entries complete for last 90 days',
        evidence: 'Sampled 20 entries.',
        conformity: 'CONFORM',
      },
    ],
    findings: [
      {
        id: 'find-1',
        auditId: 'aud-2',
        description: 'No humidity monitoring in packaging area',
        severity: 'MAJOR',
        ncId: 'nc-1',
        createdAt: iso(-19),
      },
    ],
  },
];

export const seedAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'user-admin',
    userName: 'Alice Martin',
    action: 'CREATE',
    entity: 'Invitation',
    entityId: 'inv-1',
    details: 'Invited newhire@demo.com as EMPLOYEE',
    timestamp: iso(-2),
  },
  {
    id: 'log-2',
    userId: 'user-qm',
    userName: 'Quentin Moreau',
    action: 'UPDATE',
    entity: 'Document',
    entityId: 'doc-1',
    details: 'Uploaded new version 1.1',
    timestamp: iso(-10),
  },
  {
    id: 'log-3',
    userId: 'user-emp',
    userName: 'Emma Bernard',
    action: 'CREATE',
    entity: 'NonConformity',
    entityId: 'nc-1',
    details: 'Reported NC-2026-001',
    timestamp: iso(-12),
  },
  {
    id: 'log-4',
    userId: 'user-auditor',
    userName: 'Alex Dupont',
    action: 'UPDATE',
    entity: 'Audit',
    entityId: 'aud-2',
    details: 'Marked audit COMPLETED with 1 finding',
    timestamp: iso(-19),
  },
];
